//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentHub.Entities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringTable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringTable() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgentHub.Entities.StringTable", typeof(StringTable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đã được kích hoạt bằng email trước đây..
        /// </summary>
        public static string AccountIsAlreadyConfirmedEmail {
            get {
                return ResourceManager.GetString("AccountIsAlreadyConfirmedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chào {0},&lt;br/&gt;&lt;br/&gt;Để kích hoạt tài khoản của bạn, vui lòng &lt;a href={1}&gt;nhấp chuột vào đây&lt;/a&gt; hoặc mở trình duyệt với liên kết này: {1}&lt;br/&gt;&lt;br/&gt;Trân trọng,&lt;br/&gt;KuuParking Team.
        /// </summary>
        public static string AccountRegisterEmailConfirmationBody {
            get {
                return ResourceManager.GetString("AccountRegisterEmailConfirmationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quận/Huyện.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không trùng khớp..
        /// </summary>
        public static string ConfirmPasswordDonotMatch {
            get {
                return ResourceManager.GetString("ConfirmPasswordDonotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KuuParking.com: Kích hoạt tài khoản của bạn..
        /// </summary>
        public static string ConfirmYourAccount {
            get {
                return ResourceManager.GetString("ConfirmYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xã/Phường.
        /// </summary>
        public static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không hợp lệ..
        /// </summary>
        public static string EmailIsNotFound {
            get {
                return ResourceManager.GetString("EmailIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the record of id: {0}..
        /// </summary>
        public static string ErrorCanNotFindTheRecord {
            get {
                return ResourceManager.GetString("ErrorCanNotFindTheRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chào {0},&lt;br/&gt;&lt;br/&gt;Để đặt lại mật khẩu của bạn, vui lòng &lt;a href={1}&gt;nhấp chuột vào đây&lt;/a&gt; hoặc mở trình duyệt với liên kết này: {1}&lt;br/&gt;&lt;br/&gt;Trân trọng,&lt;br/&gt;KuuParking Team.
        /// </summary>
        public static string ForgotPasswordEmailConfirmationBody {
            get {
                return ResourceManager.GetString("ForgotPasswordEmailConfirmationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KuuParking cho phép tận dụng garage hay không gian trống của bạn làm bãi đậu/đỗ xe ôtô và người dùng dễ dàng tìm kiếm bãi đậu/đỗ xe của bạn theo tên đường, thành phố, hay địa chỉ trên bản đồ trực tuyến (Google map). Người dùng có thể đặt mua và thanh toán trực tuyến vị trí đậu xe mong muốn. KuuParking còn cho phép bạn quản lý việc xe vào/ra tại bãi đậu xe của bạn và quản lý chi tiết doanh thu trên máy tính hay điện thoại thông minh ở bất cứ đâu bạn có kết nối internet..
        /// </summary>
        public static string HomePageDescription {
            get {
                return ResourceManager.GetString("HomePageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KuuParking - Tìm bãi đậu xe ôtô theo tên đường, thành phố, hay địa chỉ.
        /// </summary>
        public static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sai tên tài khoản hoặc mật khẩu.
        /// </summary>
        public static string IncorrectUsernamePassword {
            get {
                return ResourceManager.GetString("IncorrectUsernamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không còn chỗ đậu xe trống.
        /// </summary>
        public static string NoSlotsLeft {
            get {
                return ResourceManager.GetString("NoSlotsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bãi đậu xe {0} không còn chỗ trống.
        /// </summary>
        public static string NotAvaliableSlotFromProvider {
            get {
                return ResourceManager.GetString("NotAvaliableSlotFromProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method is not supported..
        /// </summary>
        public static string NotSupportedMethod {
            get {
                return ResourceManager.GetString("NotSupportedMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KuuParking cho phép bạn cập nhật thông tin các bãi đậu xe ôtô của bạn, quản lý việc xe vào/ra và báo cáo chi tiết doanh thu của các bãi đậu xe..
        /// </summary>
        public static string ProviderAdminPageDescription {
            get {
                return ResourceManager.GetString("ProviderAdminPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KuuParking - Quản lý bãi đậu xe ôtô của bạn.
        /// </summary>
        public static string ProviderAdminPageTitle {
            get {
                return ResourceManager.GetString("ProviderAdminPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy bãi đậu xe.
        /// </summary>
        public static string ProviderIsNotFound {
            get {
                return ResourceManager.GetString("ProviderIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung điều khoản thỏa thuận giữa KuuParking và người cung cấp thông tin bãi đậu xe.
        /// </summary>
        public static string ProviderPrivacyStatementPageDescription {
            get {
                return ResourceManager.GetString("ProviderPrivacyStatementPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KuuParking - Điều khoản thỏa thuận với người cung cấp bãi đậu xe ôtô.
        /// </summary>
        public static string ProviderPrivacyStatementPageTitle {
            get {
                return ResourceManager.GetString("ProviderPrivacyStatementPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KuuParking cho phép tận dụng garage hay không gian trống của bạn làm bãi đậu/đỗ xe ôtô. Chỉ cần đăng ký thông tin là bãi đậu xe của bạn có thể được người dùng tìm kiếm theo tên đường, thành phố, hay địa chỉ trên bản đồ trực tuyến/Googlemap. Người dùng có thể đặt mua và thanh toán trực tuyến vị trí đậu xe mong muốn..
        /// </summary>
        public static string ProviderRegisterPageDescription {
            get {
                return ResourceManager.GetString("ProviderRegisterPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KuuParking - Đăng ký bãi đậu xe ôtô trên bản đồ tìm kiếm.
        /// </summary>
        public static string ProviderRegisterPageTitle {
            get {
                return ResourceManager.GetString("ProviderRegisterPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bãi đậu xe chưa có chỗ đậu xe..
        /// </summary>
        public static string ProviderSlotsAreEmpty {
            get {
                return ResourceManager.GetString("ProviderSlotsAreEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu lấy lại mật khẩu không hợp lệ hoặc đã hết hạn..
        /// </summary>
        public static string ResetPasswordRequestIsExpired {
            get {
                return ResourceManager.GetString("ResetPasswordRequestIsExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KuuParking.com: Cài đặt lại mật khẩu của bạn.
        /// </summary>
        public static string ResetYourPasswordSubject {
            get {
                return ResourceManager.GetString("ResetYourPasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã bảo mật.
        /// </summary>
        public static string SecurityCode {
            get {
                return ResourceManager.GetString("SecurityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỗ đậu xe đang được sử dụng..
        /// </summary>
        public static string SlotBeingUsed {
            get {
                return ResourceManager.GetString("SlotBeingUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy chỗ trống đậu xe.
        /// </summary>
        public static string SlotIsNotFound {
            get {
                return ResourceManager.GetString("SlotIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉnh/Thành.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy người dùng với email/số điện thoại {0}.
        /// </summary>
        public static string UserNotFoundByEmail {
            get {
                return ResourceManager.GetString("UserNotFoundByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu có ít nhất 6 ký tự trong đó ít nhất có 1 ký tự in thường từ &apos;a&apos; - &apos;z&apos; và có ít nhất một ký tự in hoa từ &apos;A&apos; - &apos;Z&apos;..
        /// </summary>
        public static string ValidPasswordPolicy {
            get {
                return ResourceManager.GetString("ValidPasswordPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã bảo mật của bạn là: {0}.
        /// </summary>
        public static string YourSecurityCodeIs {
            get {
                return ResourceManager.GetString("YourSecurityCodeIs", resourceCulture);
            }
        }
    }
}
